services:
  portfoliobench:
    build: .
    restart: unless-stopped
    container_name: portfoliobench
    entrypoint: python
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    command: >
      ./user_data/run_custom.py webserver
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --config /freqtrade/user_data/config.json
